Internal Server Error: /commande
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\main\views.py", line 241, in commande
    ref, name, qty, id=i.split(':')
ValueError: not enough values to unpack (expected 4, got 3)
Internal Server Error: /marks/products/1
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\main\views.py", line 296, in products
    return render(request, 'products.html', {'products':products, 'title':'Produits de '+str(c), 'category':c})
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '=='admin'' from 'user.groups.all.0=='admin''
Internal Server Error: /marks/products/1
Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'user.groups.all.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\hp\Desktop\projects\otoprts\main\views.py", line 296, in products
    return render(request, 'products.html', {'products':products, 'title':'Produits de '+str(c), 'category':c})
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\hp\Desktop\projects\otoprts\vauto\lib\site-packages\django\template\base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 161: 'user.groups.all.0', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
